"""initial schema

Revision ID: 1676911ec139
Revises: 
Create Date: 2026-02-24 12:59:09.546478

"""
from typing import Sequence, Union
import sqlalchemy_utils

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1676911ec139'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sqlalchemy_utils.types.email.EmailType(length=255), nullable=False),
    sa.Column('password', sa.LargeBinary(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('goals',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('DRAFT', 'ACTIVE', 'PAUSED', 'COMPLETED', 'CANCELLED', name='goal_status'), nullable=False),
    sa.Column('priority', sa.Integer(), nullable=True),
    sa.Column('target_date', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_goals_user_id'), 'goals', ['user_id'], unique=False)
    op.create_table('tokens_users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('token_hash', sa.LargeBinary(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('rotated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tokens_users_token_hash'), 'tokens_users', ['token_hash'], unique=True)
    op.create_index(op.f('ix_tokens_users_user_id'), 'tokens_users', ['user_id'], unique=False)
    op.create_table('goal_stages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('goal_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('detailed_instructions', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('NOT_STARTED', 'IN_PROGRESS', 'COMPLETED', 'SKIPPED', name='stage_status'), nullable=False),
    sa.Column('order_index', sa.Integer(), nullable=False),
    sa.Column('is_milestone', sa.Boolean(), nullable=True),
    sa.Column('actual_start_date', sa.DateTime(), nullable=True),
    sa.Column('actual_end_date', sa.DateTime(), nullable=True),
    sa.Column('estimated_duration_hours', sa.Float(), nullable=True),
    sa.Column('difficulty_level', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['goal_id'], ['goals.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_goal_order', 'goal_stages', ['goal_id', 'order_index'], unique=False)
    op.create_index(op.f('ix_goal_stages_goal_id'), 'goal_stages', ['goal_id'], unique=False)
    op.create_table('stage_dependencies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('prerequisite_stage_id', sa.Integer(), nullable=False),
    sa.Column('dependent_stage_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('prerequisite_stage_id != dependent_stage_id', name='no_self_dependency'),
    sa.ForeignKeyConstraint(['dependent_stage_id'], ['goal_stages.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['prerequisite_stage_id'], ['goal_stages.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('prerequisite_stage_id', 'dependent_stage_id', name='uq_stage_dependency')
    )
    op.create_index(op.f('ix_stage_dependencies_dependent_stage_id'), 'stage_dependencies', ['dependent_stage_id'], unique=False)
    op.create_index(op.f('ix_stage_dependencies_prerequisite_stage_id'), 'stage_dependencies', ['prerequisite_stage_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_stage_dependencies_prerequisite_stage_id'), table_name='stage_dependencies')
    op.drop_index(op.f('ix_stage_dependencies_dependent_stage_id'), table_name='stage_dependencies')
    op.drop_table('stage_dependencies')
    op.drop_index(op.f('ix_goal_stages_goal_id'), table_name='goal_stages')
    op.drop_index('idx_goal_order', table_name='goal_stages')
    op.drop_table('goal_stages')
    op.drop_index(op.f('ix_tokens_users_user_id'), table_name='tokens_users')
    op.drop_index(op.f('ix_tokens_users_token_hash'), table_name='tokens_users')
    op.drop_table('tokens_users')
    op.drop_index(op.f('ix_goals_user_id'), table_name='goals')
    op.drop_table('goals')
    op.drop_table('users')
    # ### end Alembic commands ###
