"""fix token fields

Revision ID: 6e2dec2fdaed
Revises: cf25fa11523c
Create Date: 2026-01-24 15:21:15.893742

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6e2dec2fdaed'
down_revision: Union[str, Sequence[str], None] = 'cf25fa11523c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tokens_users', sa.Column('created_at', sa.DateTime(timezone=True), nullable=False))
    op.add_column('tokens_users', sa.Column('rotated_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('tokens_users', sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False))
    op.drop_column('tokens_users', 'is_active')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tokens_users', sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.drop_column('tokens_users', 'expires_at')
    op.drop_column('tokens_users', 'rotated_at')
    op.drop_column('tokens_users', 'created_at')
    # ### end Alembic commands ###
