"""fix user add email field

Revision ID: d619307681f1
Revises: 
Create Date: 2026-01-21 20:11:29.100145

"""
from typing import Sequence, Union
import sqlalchemy_utils

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd619307681f1'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sqlalchemy_utils.types.email.EmailType(length=255), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('goals',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('DRAFT', 'PLANNING', 'ACTIVE', 'PAUSED', 'COMPLETED', 'CANCELLED', name='goalstatus'), nullable=False),
    sa.Column('priority', sa.Integer(), nullable=True),
    sa.Column('target_date', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('ai_model_used', sa.String(length=100), nullable=True),
    sa.Column('ai_summary', sa.Text(), nullable=True),
    sa.Column('ai_confidence', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_goals_id'), 'goals', ['id'], unique=False)
    op.create_table('goal_stages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('goal_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('detailed_instructions', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('NOT_STARTED', 'IN_PROGRESS', 'COMPLETED', 'BLOCKED', 'SKIPPED', name='stage_status'), nullable=False),
    sa.Column('progress_percentage', sa.Integer(), nullable=True),
    sa.Column('is_milestone', sa.Boolean(), nullable=True),
    sa.Column('order_index', sa.Integer(), nullable=True),
    sa.Column('estimated_start_date', sa.DateTime(), nullable=True),
    sa.Column('estimated_end_date', sa.DateTime(), nullable=True),
    sa.Column('actual_start_date', sa.DateTime(), nullable=True),
    sa.Column('actual_end_date', sa.DateTime(), nullable=True),
    sa.Column('estimated_duration_hours', sa.Float(), nullable=True),
    sa.Column('difficulty_level', sa.Integer(), nullable=True),
    sa.Column('ai_confidence', sa.Integer(), nullable=True),
    sa.Column('position_x', sa.Float(), nullable=True),
    sa.Column('position_y', sa.Float(), nullable=True),
    sa.Column('tags', sa.JSON(), nullable=True),
    sa.Column('prerequisites', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['goal_id'], ['goals.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_goal_stages_goal_id'), 'goal_stages', ['goal_id'], unique=False)
    op.create_index(op.f('ix_goal_stages_id'), 'goal_stages', ['id'], unique=False)
    op.create_table('stage_dependencies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('prerequisite_stage_id', sa.Integer(), nullable=False),
    sa.Column('dependent_stage_id', sa.Integer(), nullable=False),
    sa.Column('dependency_type', sa.Enum('FINISH_TO_START', 'START_TO_START', 'FINISH_TO_FINISH', 'START_TO_FINISH', name='dependencytype'), nullable=False),
    sa.Column('strength', sa.Enum('REQUIRED', 'RECOMMENDED', 'OPTIONAL', name='dependencystrength'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('is_satisfied', sa.Boolean(), nullable=True),
    sa.Column('lag_days', sa.Integer(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['dependent_stage_id'], ['goal_stages.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['prerequisite_stage_id'], ['goal_stages.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('prerequisite_stage_id', 'dependent_stage_id')
    )
    op.create_index(op.f('ix_stage_dependencies_dependent_stage_id'), 'stage_dependencies', ['dependent_stage_id'], unique=False)
    op.create_index(op.f('ix_stage_dependencies_id'), 'stage_dependencies', ['id'], unique=False)
    op.create_index(op.f('ix_stage_dependencies_prerequisite_stage_id'), 'stage_dependencies', ['prerequisite_stage_id'], unique=False)
    op.create_table('user_stage_progress',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('stage_id', sa.Integer(), nullable=False),
    sa.Column('progress_percentage', sa.Integer(), nullable=False),
    sa.Column('previous_progress', sa.Integer(), nullable=True),
    sa.Column('current_status', sa.Enum('not_started', 'in_progress', 'completed', 'paused', 'blocked', name='user_stage_current_status'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('last_worked_on', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('total_time_spent_minutes', sa.Float(), nullable=True),
    sa.Column('estimated_remaining_minutes', sa.Float(), nullable=True),
    sa.Column('user_difficulty_rating', sa.Integer(), nullable=True),
    sa.Column('user_satisfaction_rating', sa.Integer(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('resources_used', sa.JSON(), nullable=True),
    sa.Column('blockers', sa.Text(), nullable=True),
    sa.Column('quality_score', sa.Integer(), nullable=True),
    sa.Column('revision_count', sa.Integer(), nullable=True),
    sa.Column('last_update_type', sa.Enum('MANUAL', 'AUTOMATIC', 'AI_SUGGESTED', 'SYSTEM', name='progresstype'), nullable=True),
    sa.Column('ai_feedback', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['stage_id'], ['goal_stages.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'stage_id')
    )
    op.create_index(op.f('ix_user_stage_progress_id'), 'user_stage_progress', ['id'], unique=False)
    op.create_index(op.f('ix_user_stage_progress_stage_id'), 'user_stage_progress', ['stage_id'], unique=False)
    op.create_index(op.f('ix_user_stage_progress_user_id'), 'user_stage_progress', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_stage_progress_user_id'), table_name='user_stage_progress')
    op.drop_index(op.f('ix_user_stage_progress_stage_id'), table_name='user_stage_progress')
    op.drop_index(op.f('ix_user_stage_progress_id'), table_name='user_stage_progress')
    op.drop_table('user_stage_progress')
    op.drop_index(op.f('ix_stage_dependencies_prerequisite_stage_id'), table_name='stage_dependencies')
    op.drop_index(op.f('ix_stage_dependencies_id'), table_name='stage_dependencies')
    op.drop_index(op.f('ix_stage_dependencies_dependent_stage_id'), table_name='stage_dependencies')
    op.drop_table('stage_dependencies')
    op.drop_index(op.f('ix_goal_stages_id'), table_name='goal_stages')
    op.drop_index(op.f('ix_goal_stages_goal_id'), table_name='goal_stages')
    op.drop_table('goal_stages')
    op.drop_index(op.f('ix_goals_id'), table_name='goals')
    op.drop_table('goals')
    op.drop_table('users')
    # ### end Alembic commands ###
