"""empty message

Revision ID: e9cb1e12e2e0
Revises: 1676911ec139
Create Date: 2026-03-17 10:32:17.969927

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

user_status_enum = postgresql.ENUM(
    'pending',
    'verified',
    name='user_status'
)


# revision identifiers, used by Alembic.
revision: str = 'e9cb1e12e2e0'
down_revision: Union[str, Sequence[str], None] = '1676911ec139'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    user_status_enum.create(op.get_bind())

    op.add_column(
        'users',
        sa.Column('status', user_status_enum, nullable=False)
    )
    # op.add_column('users', sa.Column('status', sa.Enum('PENDING', 'VERIFIED', name='user_status'), nullable=False))
    # # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'status')
    # ### end Alembic commands ###
