"""empty message

Revision ID: ef610515d708
Revises: 59524ef77d5a
Create Date: 2026-03-18 08:53:39.535009

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ef610515d708'
down_revision: Union[str, Sequence[str], None] = '59524ef77d5a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('goal_stages', sa.Column('latitude', sa.Float(), nullable=True))
    op.add_column('goal_stages', sa.Column('longitude', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('goal_stages', 'longitude')
    op.drop_column('goal_stages', 'latitude')
    # ### end Alembic commands ###
